# Generated by Django 4.1.7 on 2023-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0002_delete_customuser_delete_studentsign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classesattended',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='totalclasses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
